services:
    poetry:
        image: poetry-base
        build:
            context: .
            dockerfile: poetry.Dockerfile
    tabpy:
        image: tabpy
        depends_on:
            - poetry
        build:
            context: .
            dockerfile: tabpy.Dockerfile
            target: deployment
        # command:
        #     - tabpy
        #     - --disable-auth-warning
        environment:
            PYTHONPATH: .
        ports:
            - "8001:9004"
        volumes:
            - ./log:/log
            - ./data/cache:/cache
        restart: always
