services:
    poetry:
        image: poetry-base
        build:
            context: .
            dockerfile: poetry.Dockerfile
    tabpy:
        image: tabpy
        depends_on:
            - poetry
        build:
            context: .
            dockerfile: tabpy.Dockerfile
        command:
            - tabpy
            - --disable-auth-warning
            - --config
            - ./tabpy.conf
        environment:
            PYTHONPATH: .
        ports:
            - "8001:9004"
        volumes:
            - ./log:/tabpy/log
            - ./data/cache:/tabpy/cache
        restart: always
